language: node_js
node_js:
  - 6
  - 8

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.28.4

cache:
  yarn: true
  directories:
    - ".eslintcache"
    - "node_modules"
